version: '3.4'

services:
  company:
    tty: true
    ports:
      - "10083:80"
    working_dir: /app
    volumes:
      - ../company:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: dev.Dockerfile

  poi:
    tty: true
    ports:
      - "10082:80"
    working_dir: /app
    volumes:
      - ../poi:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: dev.Dockerfile

  usage:
    tty: true
    ports:
      - "10081:80"
    working_dir: /app
    volumes:
      - ../usage:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: dev.Dockerfile

  userfrontend:
    tty: true
    ports:
      - "10080:80"
    working_dir: /app
    volumes:
      - ../user-frontend/client:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: dev.Dockerfile

networks:
  micros-network:
    driver: bridge